<template>
  <div ref="chart" class="chart-container">
    <svg width="600" height="600">
      <g ref="ringsGroup"></g>
    </svg>
  </div>
</template>

<script>
import { onMounted, ref } from 'vue' // sample animation generated by ChatGPT (according to Chat I can use GSAP to animate D3 stuff)
import * as d3 from 'd3'
import gsap from 'gsap'

export default {
  setup() {
    const chart = ref(null)
    const ringsGroup = ref(null)

    onMounted(() => {
      const svgWidth = 600
      const svgHeight = 600
      const centerX = svgWidth / 2
      const centerY = svgHeight / 2

      const numRings = 3
      const numCirclesPerRing = 6

      const rings = d3.select(ringsGroup.value)

      for (let i = 0; i < numRings; i++) {
        const radius = (i + 1) * 100
        const ringGroup = rings
          .append('g')
          .attr('class', `ring-${i}`)
          .attr('transform', `translate(${centerX}, ${centerY})`)

        for (let j = 0; j < numCirclesPerRing; j++) {
          const angle = ((2 * Math.PI) / numCirclesPerRing) * j
          const x = radius * Math.cos(angle)
          const y = radius * Math.sin(angle)

          ringGroup
            .append('circle')
            .attr('cx', x)
            .attr('cy', y)
            .attr('r', 15)
            .attr('fill', d3.schemeCategory10[i % 10])
        }
      }

      gsap.to(ringsGroup.value, {
        rotation: 360,
        repeat: -1,
        duration: 10,
        ease: 'linear',
        transformOrigin: 'center center',
      })
    })

    return {
      chart,
      ringsGroup,
    }
  },
}
</script>

<style scoped>
.chart-container {
  width: 600px;
  height: 600px;
  border: 1px solid #ccc;
  margin: 0 auto;
}
</style>
